### ISSUE TITLE
modify for Angular 2?

### ISSUE THREAD

**Issue by mckinleymedia** [yobryon/ngx-barcode#1]
I tried installing this in Angular 2. It doesn't seem to work. Any tips for what I need to do to modify this to work with Angular 2?

**Comment by yobryon** [comment]
looks like there was a problem packing 0.2.0...    I've re-published this properly and bumped to v0.2.1.  Try again -- it *should* work fine with angular2 -- but if you still have trouble with it after bumping to 0.2.1, i'll take a deeper look.

**Comment by mckinleymedia** [comment]
Thanks! The module is now found, but I now get this error:
"export 'Renderer2' was not found in '@angular/core' 
I know that's one of the changes between Angular 2 and 4. Do you have a fix for that?

**Comment by nadircan** [comment]
> Thanks! The module is now found, but I now get this error:
"export 'Renderer2' was not found in ''
I know that's one of the changes between Angular 2 and 4. Do you have a fix for that?

I get the same error. What is the solution?

**Comment by mckinleymedia** [comment]
I couldn't get the module to work, so I just ended up importing the jsbarcode library directly like this:
`npm install jsbarcode -S`
then in the component html: 
`<canvas class="jsbarcode"></canvas>
`
then in component js I added these 4 things:
`let jsbarcode = require('jsbarcode');
`
and
`  bcInit = false;
`
and 
`  ngAfterViewChecked() {
    this.createBarcode();
  }
`
and 
`  createBarcode() {
    if (!this.bcInit) {
      let element = document.getElementsByClassName("jsbarcode")[0];
      if (element) {
        jsbarcode(element, this.data.id, {
          format: 'CODE128'
         });
        this.bcInit = true;
      }
    }
  }
`
Not really the best way to do it, using getElementsByClassName, but it works. Hope this helps.

**Comment by mark-win** [comment]
Could not reproduce using Angular 4.2.2 and ngx-barcode 0.2.1. Everything worked out of the box as described in readme.md.

**Comment by mckinleymedia** [comment]
@mark-win - Per the title of this thread, my question was specifically for Angular 2, not Angular 4.

**Comment by yobryon** [comment]
In a desire to keep this compatible with server-side rendering, and to keep close to the direction of the angular renderer, this project will keep its use of Renderer2 and require angular 4 minimum. Renderer is deprecated in favor of Renderer2, where the former will probably be removed at some point in the not-too-distant future. The angular team has kept things fairly minimal in terms of overall effort to accommodate their API changes over time, so hopefully projects can migrate up to angular 4/5+.

**Comment by ramanbalaji** [comment]
I'm looking for an ionic angular js MSI barcode scanner.  Can the ngx-barcode be used for scanning MSI barcodes or only for creating MSI barcodes?  Any help is greatly appreciated.
