### ISSUE TITLE
Can't seem to set format

### ISSUE THREAD

**Issue by rohecom** [yobryon/ngx-barcode#2]
I use this package in a angular2 cli project, works fine. But it always seem to render with the CODE128 format, I'd like to use EAN (13)

I use it like this, where currentProduct.Barcode = 2072400208056

`<ngx-barcode [bc-element-type]="svg" 
                        [bc-format]="EAN" 
                        [bc-font-size]="13" 
                        [bc-height]="32" 
                        [bc-background]="transparent" 
                        [bc-value]="currentProduct.Barcode" 
                        [bc-display-value]="true">
 </ngx-barcode>`

Any thoughts?

angular/cli: 1.1.0
node: 7.9.0
os: linux x64

angular/animations@4.2.2
angular/cli@1.1.0
angular/common@4.2.2
angular/compiler@4.2.2
angular/compiler-cli@4.2.2
angular/core@4.2.2
angular/flex-layout@2.0.0-beta.8
angular/forms@4.2.2
angular/http@4.2.2
angular/language-service@4.2.2
angular/material@2.0.0-beta.6
angular/platform-browser@4.2.2
angular/platform-browser-dynamic@4.2.2
angular/router@4.2.2
types/cordova@0.0.34
types/cordova-plugin-device@0.0.3
types/hammerjs@2.0.34
types/jasmine@2.5.45
types/lodash@4.14.66
types/node@6.0.78
codelyzer@3.0.1
core-js@2.4.1
hammerjs@2.0.8
jasmine-core@2.6.3
jasmine-spec-reporter@4.1.0
karma@1.7.0
karma-chrome-launcher@2.1.1
karma-cli@1.0.1
karma-coverage-istanbul-reporter@1.3.0
karma-jasmine@1.1.0
karma-jasmine-html-reporter@0.2.2
lodash@4.17.4
ng2-truncate@1.3.7
ngx-barcode@0.2.1
ngx-pipes@1.6.1
protractor@5.1.2
rxjs@5.4.1
ts-node@3.0.6
tslint@5.3.2
typescript@2.3.4
zone.js@0.8.12

**Comment by yobryon** [comment]
try using the following:
`<ngx-barcode [bc-element-type]="svg" bc-format="EAN" [bc-font-size]="13" [bc-height]="32" [bc-background]="transparent" [bc-value]="currentProduct.Barcode" [bc-display-value]="true"> </ngx-barcode>
`
By placing the bc-format attribute in square brackets, angular would consider the value an expression, and if EAN is not a member of the class, it would be evaluated as undefined, hence giving you the default format.

**Comment by rohecom** [comment]
Ah right, I'm a dork ;-)

Thank you!

**Comment by m-tino77** [comment]
If not specified, what is the default format for bc-format?
