### ISSUE TITLE
index.js not found in v0.2.2

### ISSUE THREAD

**Issue by akana** [yobryon/ngx-barcode#3]
after update to v0.2.2, i got this error in browser
Module build failed: Error: ENOENT: no such file or directory, open 'xxx\node_modules\ngx-barcode\index.js' at Error (native)

It works fine in v0.2.1

plateform:

- ionic v3.5.0
- angular v4.1.3
- node v7.7.3
- npm v4.1.2

**Comment by yobryon** [comment]
The build/package issues should all be resolved in the new 0.2.4 version.

**Comment by yobryon** [comment]
@akana if this one works for you, please go ahead and close the issue. Thanks!

**Comment by akana** [comment]
it works. thank you very much :+1:
