### ISSUE TITLE
Trying to install for Angular 12 and get an error.

### ISSUE THREAD

**Issue by mwiginton** [yobryon/ngx-barcode#56]
I get this error when I try to install this package on an app using Angular 12. I was of the impression that this tool is compatible with Angular versions 4 and up. Below is my error. Any tips on how to resolve this?

`npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @angular/core@12.0.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^4.0.0" from ngx-barcode@0.3.0
npm ERR! node_modules/ngx-barcode
npm ERR!   ngx-barcode@"^0.3.0" from the root project
npm ERR! `

**Comment by chrisbendel** [comment]
@mwiginton  Ran into the same issue, turns out there's an updated fork to work with angular 8+ here https://github.com/efgiese/ngx-barcode6

**Comment by mwiginton** [comment]
@chrisbendel yes I happened to stumble upon this one and it suits my needs perfectly. Thank you!
